### PR TITLE
Add Content-Type to responses

### PR DESCRIPTION
**Pull request by bre7**
Related to #20 

Why does NIO add headers in lowercase 😢 

-------

The test that doesn't pass is a false positive: https://github.com/vapor/vapor/blob/master/Tests/VaporTests/ApplicationTests.swift#L289

Compares

> age=3&luckyNumbers[]=5&luckyNumbers[]=7&name=Vapor
with
> name=Vapor&age=3&luckyNumbers[]=5&luckyNumbers[]=7

They have the same encoded values but in different order (doesn't matter).
_Possible_ reason: Attributes are ordered alphabetically ?

### CODE REVIEW

**Comment by tanner0101** [comment]
Yeah the Vapor tests are my fault, I am fixing those soon.

**Comment by bre7** [comment]
👍

**Comment by tanner0101** [comment]
thanks :)

**Comment by tanner0101** [comment]
What's your slack username btw (are you in slack?)

**Comment by bre7** [comment]
"Nathan" (U9KT7LD97), I'm not always there but can hop on if you need me to (easier to talk about PRs) 😉

**Pull request merged**
