### PR TITLE
fixes code coverage build issue

### PR DESCRIPTION
**Pull request by valeriomazzeo**
fixes https://github.com/vapor/vapor/issues/1624

### CODE REVIEW

**Comment by tanner0101** [comment]
@valeriomazzeo I think you meant to make this against the 2.x branch?

**Comment by vzsg** [comment]
Yes, it is. Unfortunately there's no vapor-2 branch in this repo, and neither @0xTim nor me have been able to push one.

(Something changed recently in the organization permissions.)

**Comment by valeriomazzeo** [comment]
@tanner0101 if you push a vapor 2 branch, I can then change the base branch of the pull request.

**Comment by tanner0101** [comment]
@vzsg hmm, seems like it was just this package. Permissions should be back to normal now.

**Pull request merged**
